# Site
name: "Warm Bananas"
title: "Warm Bananas"
description: "Totally random stuff."
banner-message: "What's happening?"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
url: https://www.warmbananas.com
google-tag-manager: "GTM-TSHL42B"
disqus: 'https-www-warmbananas-com'
# mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: admin@warmbananas.com

# Authors
authors:
  avi:
    name: "Christian Avi Bulan"
    display_name: Avi
    gravatar: 51a0463561379f427830b54d94cc05f6
    email: christianavibulan@gmail.com
    web: https://www.warmbananas.com
    twitter: christianaviii
    description: "Hobbyist. Only does these kinds of things for fun."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Facebook Messenger
messenger:
  page-id: "103714821167720"
  theme-color: "#000000"
  logged-in-greeting: "Hi! How can we help you?"
  logged-out-greeting: "Hi! How can we help you?"
      
# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-5326267743024936"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
